.\"    $​Id$
.\" Copyright (c) 2015, Mark Heily <mark@heily.com>
.\" All rights reserved.
.\" 
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions are met:
.\" 
.\" * Redistributions of source code must retain the above copyright notice, this
.\"   list of conditions and the following disclaimer.
.\" 
.\" * Redistributions in binary form must reproduce the above copyright notice,
.\"   this list of conditions and the following disclaimer in the documentation
.\"   and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
.\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
.\" DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
.\" CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\" OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
.\" OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\" 
.Dd December 26, 2015
.Dt ipc 7
.Os
.Sh NAME
.Nm ipc
.Nd a mechanism for inter-process communication
.Sh SYNOPSIS
.In ipc.h
.Sh DESCRIPTION
Processes running under a non-privileged user ID may communicate with
.Nm
to request the ability to bind to the IPC namespace.
.Sh API
.Ft "int"
.Fn ipc_accept "int s" ;
.Pp
.Ft "int"
.Fo ipc_bind
.Fa "int domain"
.Fa "const char *service"
.Fa "int version"
.Fc ;
.Pp
.Ft "int"
.Fo ipc_connect
.Fa "int domain"
.Fa "const char *service"
.Fa "int version" 
.Fc ;
.Pp
.Ft "int"
.Fo ipc_write
.Fa "int s"
.Fa "const struct iovec *iov"
.Fa "int iovcnt"
.Fc ;
.Pp
.Ft "int"
.Fo ipc_read
.Fa "int s"
.Fa "struct iovec *iov"
.Fa "int *iovcnt"
.Fc ;
.Pp
.Ft "int"
.Fo ipc_close
.Fa "int s"
.Fc ;
.Sh EXIT STATUS
.Ex -std
.Sh ENVIRONMENT
This daemon does not rely on any environment variables.
.Sh AUTHORS
.An Mark Heily
.Mt <mark@heily.com> .